[2024-09-03T13:29:16.717+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: k9_etl_dag_v5.create_k9_table scheduled__2024-09-02T00:00:00+00:00 [queued]>
[2024-09-03T13:29:16.728+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: k9_etl_dag_v5.create_k9_table scheduled__2024-09-02T00:00:00+00:00 [queued]>
[2024-09-03T13:29:16.729+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2024-09-03T13:29:16.739+0000] {taskinstance.py:1380} INFO - Executing <Task(SQLExecuteQueryOperator): create_k9_table> on 2024-09-02 00:00:00+00:00
[2024-09-03T13:29:16.753+0000] {standard_task_runner.py:57} INFO - Started process 1585 to run task
[2024-09-03T13:29:16.773+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'k9_etl_dag_v5', 'create_k9_table', 'scheduled__2024-09-02T00:00:00+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/k9_etl_dag_v5.py', '--cfg-path', '/tmp/tmp5yqovgs_']
[2024-09-03T13:29:16.776+0000] {standard_task_runner.py:85} INFO - Job 35: Subtask create_k9_table
[2024-09-03T13:29:16.862+0000] {task_command.py:415} INFO - Running <TaskInstance: k9_etl_dag_v5.create_k9_table scheduled__2024-09-02T00:00:00+00:00 [running]> on host 2624bebdd8ee
[2024-09-03T13:29:17.161+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='k9_etl_dag_v5' AIRFLOW_CTX_TASK_ID='create_k9_table' AIRFLOW_CTX_EXECUTION_DATE='2024-09-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-02T00:00:00+00:00'
[2024-09-03T13:29:17.162+0000] {sql.py:274} INFO - Executing: 
        CREATE TABLE IF NOT EXISTS k9_facts_v5 (
            id SERIAL PRIMARY KEY,
            fact_id INTEGER,
            created_date TIMESTAMP,
            description TEXT,
            category VARCHAR(50),
            version INTEGER,
            is_current BOOLEAN,
            is_deleted BOOLEAN DEFAULT FALSE
        );
        
[2024-09-03T13:29:17.171+0000] {base.py:73} INFO - Using connection ID 'k9_care' for task execution.
[2024-09-03T13:29:17.208+0000] {base.py:73} INFO - Using connection ID 'k9_care' for task execution.
[2024-09-03T13:29:17.286+0000] {sql.py:418} INFO - Running statement: 
        CREATE TABLE IF NOT EXISTS k9_facts_v5 (
            id SERIAL PRIMARY KEY,
            fact_id INTEGER,
            created_date TIMESTAMP,
            description TEXT,
            category VARCHAR(50),
            version INTEGER,
            is_current BOOLEAN,
            is_deleted BOOLEAN DEFAULT FALSE
        );
        , parameters: None
[2024-09-03T13:29:17.330+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 280, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 392, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 423, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "pg_class_relname_nsp_index"
DETAIL:  Key (relname, relnamespace)=(k9_facts_v5_id_seq, 2200) already exists.

[2024-09-03T13:29:17.345+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=k9_etl_dag_v5, task_id=create_k9_table, execution_date=20240902T000000, start_date=20240903T132916, end_date=20240903T132917
[2024-09-03T13:29:17.363+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 35 for task create_k9_table (duplicate key value violates unique constraint "pg_class_relname_nsp_index"
DETAIL:  Key (relname, relnamespace)=(k9_facts_v5_id_seq, 2200) already exists.
; 1585)
[2024-09-03T13:29:17.424+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-09-03T13:29:17.500+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
