[2024-09-03T14:00:09.054+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: k9_etl_dag_v6.execute_sql manual__2024-09-03T14:00:01.821795+00:00 [queued]>
[2024-09-03T14:00:09.073+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: k9_etl_dag_v6.execute_sql manual__2024-09-03T14:00:01.821795+00:00 [queued]>
[2024-09-03T14:00:09.073+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2024-09-03T14:00:09.081+0000] {taskinstance.py:1380} INFO - Executing <Task(_PythonDecoratedOperator): execute_sql> on 2024-09-03 14:00:01.821795+00:00
[2024-09-03T14:00:09.092+0000] {standard_task_runner.py:57} INFO - Started process 2172 to run task
[2024-09-03T14:00:09.098+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'k9_etl_dag_v6', 'execute_sql', 'manual__2024-09-03T14:00:01.821795+00:00', '--job-id', '97', '--raw', '--subdir', 'DAGS_FOLDER/k9_etl_dag_v6.py', '--cfg-path', '/tmp/tmpukuqnqfg']
[2024-09-03T14:00:09.102+0000] {standard_task_runner.py:85} INFO - Job 97: Subtask execute_sql
[2024-09-03T14:00:09.148+0000] {task_command.py:415} INFO - Running <TaskInstance: k9_etl_dag_v6.execute_sql manual__2024-09-03T14:00:01.821795+00:00 [running]> on host 2624bebdd8ee
[2024-09-03T14:00:09.206+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='k9_etl_dag_v6' AIRFLOW_CTX_TASK_ID='execute_sql' AIRFLOW_CTX_EXECUTION_DATE='2024-09-03T14:00:01.821795+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-03T14:00:01.821795+00:00'
[2024-09-03T14:00:09.331+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/k9_etl_dag_v6.py", line 145, in execute_sql
    new_facts = set(item['fact_id'] for item in transformed_data)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom_arg.py", line 268, in __iter__
    raise TypeError("'XComArg' object is not iterable")
TypeError: 'XComArg' object is not iterable
[2024-09-03T14:00:09.360+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=k9_etl_dag_v6, task_id=execute_sql, execution_date=20240903T140001, start_date=20240903T140009, end_date=20240903T140009
[2024-09-03T14:00:09.380+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 97 for task execute_sql ('XComArg' object is not iterable; 2172)
[2024-09-03T14:00:09.408+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-09-03T14:00:09.445+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
