[2024-09-03T13:48:38.337+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: k9_etl_dag_v5.execute_sql manual__2024-09-03T13:48:32.520738+00:00 [queued]>
[2024-09-03T13:48:38.341+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: k9_etl_dag_v5.execute_sql manual__2024-09-03T13:48:32.520738+00:00 [queued]>
[2024-09-03T13:48:38.341+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2024-09-03T13:48:38.347+0000] {taskinstance.py:1380} INFO - Executing <Task(_PythonDecoratedOperator): execute_sql> on 2024-09-03 13:48:32.520738+00:00
[2024-09-03T13:48:38.349+0000] {standard_task_runner.py:57} INFO - Started process 1952 to run task
[2024-09-03T13:48:38.352+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'k9_etl_dag_v5', 'execute_sql', 'manual__2024-09-03T13:48:32.520738+00:00', '--job-id', '76', '--raw', '--subdir', 'DAGS_FOLDER/k9_etl_dag_v5.py', '--cfg-path', '/tmp/tmpgifi9t69']
[2024-09-03T13:48:38.352+0000] {standard_task_runner.py:85} INFO - Job 76: Subtask execute_sql
[2024-09-03T13:48:38.376+0000] {task_command.py:415} INFO - Running <TaskInstance: k9_etl_dag_v5.execute_sql manual__2024-09-03T13:48:32.520738+00:00 [running]> on host 2624bebdd8ee
[2024-09-03T13:48:38.421+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='k9_etl_dag_v5' AIRFLOW_CTX_TASK_ID='execute_sql' AIRFLOW_CTX_EXECUTION_DATE='2024-09-03T13:48:32.520738+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-03T13:48:32.520738+00:00'
[2024-09-03T13:48:38.439+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/k9_etl_dag_v5.py", line 163, in execute_sql
    cursor.execute(query)
psycopg2.errors.UndefinedFunction: operator does not exist: integer = character varying
LINE 5:                 WHERE fact_id = 'f8d7b346e3b1b8d5155886cc0c0...
                                      ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.

[2024-09-03T13:48:38.444+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=k9_etl_dag_v5, task_id=execute_sql, execution_date=20240903T134832, start_date=20240903T134838, end_date=20240903T134838
[2024-09-03T13:48:38.449+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 76 for task execute_sql (operator does not exist: integer = character varying
LINE 5:                 WHERE fact_id = 'f8d7b346e3b1b8d5155886cc0c0...
                                      ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.
; 1952)
[2024-09-03T13:48:38.453+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-09-03T13:48:38.468+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
