[2024-09-03T05:24:22.035+0000] {processor.py:157} INFO - Started process (PID=927) to work on /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T05:24:22.036+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/k9_etl_dag_v2.py for tasks to queue
[2024-09-03T05:24:22.039+0000] {logging_mixin.py:151} INFO - [2024-09-03T05:24:22.039+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T05:24:22.063+0000] {logging_mixin.py:151} INFO - [2024-09-03T05:24:22.058+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/k9_etl_dag_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/k9_etl_dag_v2.py", line 160, in <module>
    create_pet_table >> extracted_data >> transformed_data >> [load_to_file, update_check] >> insert_queries >> load_to_db >> send_notification
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 103, in __rshift__
    self.set_downstream(other)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom_arg.py", line 155, in set_downstream
    operator.set_downstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 261, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 213, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
AttributeError: '_TaskDecorator' object has no attribute 'update_relative'
[2024-09-03T05:24:22.063+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T05:24:22.081+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/k9_etl_dag_v2.py took 0.050 seconds
[2024-09-03T05:24:52.367+0000] {processor.py:157} INFO - Started process (PID=936) to work on /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T05:24:52.369+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/k9_etl_dag_v2.py for tasks to queue
[2024-09-03T05:24:52.372+0000] {logging_mixin.py:151} INFO - [2024-09-03T05:24:52.372+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T05:24:52.409+0000] {logging_mixin.py:151} INFO - [2024-09-03T05:24:52.407+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/k9_etl_dag_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/k9_etl_dag_v2.py", line 160, in <module>
    create_pet_table >> extracted_data >> transformed_data >> [load_to_file, update_check] >> insert_queries >> load_to_db >> send_notification
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 103, in __rshift__
    self.set_downstream(other)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom_arg.py", line 155, in set_downstream
    operator.set_downstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 261, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 213, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
AttributeError: '_TaskDecorator' object has no attribute 'update_relative'
[2024-09-03T05:24:52.409+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T05:24:52.425+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/k9_etl_dag_v2.py took 0.060 seconds
[2024-09-03T05:25:22.658+0000] {processor.py:157} INFO - Started process (PID=945) to work on /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T05:25:22.659+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/k9_etl_dag_v2.py for tasks to queue
[2024-09-03T05:25:22.662+0000] {logging_mixin.py:151} INFO - [2024-09-03T05:25:22.662+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T05:25:22.680+0000] {logging_mixin.py:151} INFO - [2024-09-03T05:25:22.678+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/k9_etl_dag_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/k9_etl_dag_v2.py", line 160, in <module>
    create_pet_table >> extracted_data >> transformed_data >> [load_to_file, update_check] >> insert_queries >> load_to_db >> send_notification
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 103, in __rshift__
    self.set_downstream(other)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom_arg.py", line 155, in set_downstream
    operator.set_downstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 261, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 213, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
AttributeError: '_TaskDecorator' object has no attribute 'update_relative'
[2024-09-03T05:25:22.680+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T05:25:22.704+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/k9_etl_dag_v2.py took 0.055 seconds
[2024-09-03T05:25:53.020+0000] {processor.py:157} INFO - Started process (PID=954) to work on /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T05:25:53.021+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/k9_etl_dag_v2.py for tasks to queue
[2024-09-03T05:25:53.025+0000] {logging_mixin.py:151} INFO - [2024-09-03T05:25:53.024+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T05:25:53.040+0000] {logging_mixin.py:151} INFO - [2024-09-03T05:25:53.038+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/k9_etl_dag_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/k9_etl_dag_v2.py", line 160, in <module>
    create_pet_table >> extracted_data >> transformed_data >> [load_to_file, update_check] >> insert_queries >> load_to_db >> send_notification
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 103, in __rshift__
    self.set_downstream(other)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom_arg.py", line 155, in set_downstream
    operator.set_downstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 261, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 213, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
AttributeError: '_TaskDecorator' object has no attribute 'update_relative'
[2024-09-03T05:25:53.041+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T05:25:53.073+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/k9_etl_dag_v2.py took 0.057 seconds
[2024-09-03T05:26:23.480+0000] {processor.py:157} INFO - Started process (PID=963) to work on /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T05:26:23.482+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/k9_etl_dag_v2.py for tasks to queue
[2024-09-03T05:26:23.485+0000] {logging_mixin.py:151} INFO - [2024-09-03T05:26:23.485+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T05:26:23.505+0000] {logging_mixin.py:151} INFO - [2024-09-03T05:26:23.498+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/k9_etl_dag_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/k9_etl_dag_v2.py", line 160, in <module>
    create_pet_table >> extracted_data >> transformed_data >> [load_to_file, update_check] >> insert_queries >> load_to_db >> send_notification
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 103, in __rshift__
    self.set_downstream(other)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom_arg.py", line 155, in set_downstream
    operator.set_downstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 261, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 213, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
AttributeError: '_TaskDecorator' object has no attribute 'update_relative'
[2024-09-03T05:26:23.507+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T05:26:23.545+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/k9_etl_dag_v2.py took 0.070 seconds
[2024-09-03T05:26:53.863+0000] {processor.py:157} INFO - Started process (PID=972) to work on /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T05:26:53.865+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/k9_etl_dag_v2.py for tasks to queue
[2024-09-03T05:26:53.869+0000] {logging_mixin.py:151} INFO - [2024-09-03T05:26:53.869+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T05:26:53.910+0000] {logging_mixin.py:151} INFO - [2024-09-03T05:26:53.907+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/k9_etl_dag_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/k9_etl_dag_v2.py", line 160, in <module>
    create_pet_table >> extracted_data >> transformed_data >> [load_to_file, update_check] >> insert_queries >> load_to_db >> send_notification
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 103, in __rshift__
    self.set_downstream(other)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom_arg.py", line 155, in set_downstream
    operator.set_downstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 261, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 213, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
AttributeError: '_TaskDecorator' object has no attribute 'update_relative'
[2024-09-03T05:26:53.911+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T05:26:53.934+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/k9_etl_dag_v2.py took 0.076 seconds
[2024-09-03T05:27:24.268+0000] {processor.py:157} INFO - Started process (PID=981) to work on /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T05:27:24.270+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/k9_etl_dag_v2.py for tasks to queue
[2024-09-03T05:27:24.274+0000] {logging_mixin.py:151} INFO - [2024-09-03T05:27:24.273+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T05:27:24.288+0000] {logging_mixin.py:151} INFO - [2024-09-03T05:27:24.286+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/k9_etl_dag_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/k9_etl_dag_v2.py", line 160, in <module>
    create_pet_table >> extracted_data >> transformed_data >> [load_to_file, update_check] >> insert_queries >> load_to_db >> send_notification
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 103, in __rshift__
    self.set_downstream(other)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom_arg.py", line 155, in set_downstream
    operator.set_downstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 261, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 213, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
AttributeError: '_TaskDecorator' object has no attribute 'update_relative'
[2024-09-03T05:27:24.288+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T05:27:24.327+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/k9_etl_dag_v2.py took 0.063 seconds
[2024-09-03T05:27:54.594+0000] {processor.py:157} INFO - Started process (PID=990) to work on /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T05:27:54.597+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/k9_etl_dag_v2.py for tasks to queue
[2024-09-03T05:27:54.608+0000] {logging_mixin.py:151} INFO - [2024-09-03T05:27:54.607+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T05:27:54.647+0000] {logging_mixin.py:151} INFO - [2024-09-03T05:27:54.645+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/k9_etl_dag_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/k9_etl_dag_v2.py", line 160, in <module>
    create_pet_table >> extracted_data >> transformed_data >> [load_to_file, update_check] >> insert_queries >> load_to_db >> send_notification
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 103, in __rshift__
    self.set_downstream(other)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom_arg.py", line 155, in set_downstream
    operator.set_downstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 261, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 213, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
AttributeError: '_TaskDecorator' object has no attribute 'update_relative'
[2024-09-03T05:27:54.647+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T05:27:54.668+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/k9_etl_dag_v2.py took 0.085 seconds
[2024-09-03T05:28:25.013+0000] {processor.py:157} INFO - Started process (PID=999) to work on /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T05:28:25.015+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/k9_etl_dag_v2.py for tasks to queue
[2024-09-03T05:28:25.019+0000] {logging_mixin.py:151} INFO - [2024-09-03T05:28:25.018+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T05:28:25.053+0000] {logging_mixin.py:151} INFO - [2024-09-03T05:28:25.050+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/k9_etl_dag_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/k9_etl_dag_v2.py", line 160, in <module>
    create_pet_table >> extracted_data >> transformed_data >> [load_to_file, update_check] >> insert_queries >> load_to_db >> send_notification
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 103, in __rshift__
    self.set_downstream(other)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom_arg.py", line 155, in set_downstream
    operator.set_downstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 261, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 213, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
AttributeError: '_TaskDecorator' object has no attribute 'update_relative'
[2024-09-03T05:28:25.054+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T05:28:25.074+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/k9_etl_dag_v2.py took 0.065 seconds
[2024-09-03T05:28:55.390+0000] {processor.py:157} INFO - Started process (PID=1008) to work on /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T05:28:55.392+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/k9_etl_dag_v2.py for tasks to queue
[2024-09-03T05:28:55.396+0000] {logging_mixin.py:151} INFO - [2024-09-03T05:28:55.396+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T05:28:55.414+0000] {logging_mixin.py:151} INFO - [2024-09-03T05:28:55.412+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/k9_etl_dag_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/k9_etl_dag_v2.py", line 160, in <module>
    create_pet_table >> extracted_data >> transformed_data >> [load_to_file, update_check] >> insert_queries >> load_to_db >> send_notification
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 103, in __rshift__
    self.set_downstream(other)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom_arg.py", line 155, in set_downstream
    operator.set_downstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 261, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 213, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
AttributeError: '_TaskDecorator' object has no attribute 'update_relative'
[2024-09-03T05:28:55.415+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T05:28:55.436+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/k9_etl_dag_v2.py took 0.068 seconds
[2024-09-03T05:29:25.761+0000] {processor.py:157} INFO - Started process (PID=1017) to work on /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T05:29:25.763+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/k9_etl_dag_v2.py for tasks to queue
[2024-09-03T05:29:25.767+0000] {logging_mixin.py:151} INFO - [2024-09-03T05:29:25.766+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T05:29:25.782+0000] {logging_mixin.py:151} INFO - [2024-09-03T05:29:25.780+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/k9_etl_dag_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/k9_etl_dag_v2.py", line 160, in <module>
    create_pet_table >> extracted_data >> transformed_data >> [load_to_file, update_check] >> insert_queries >> load_to_db >> send_notification
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 103, in __rshift__
    self.set_downstream(other)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom_arg.py", line 155, in set_downstream
    operator.set_downstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 261, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 213, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
AttributeError: '_TaskDecorator' object has no attribute 'update_relative'
[2024-09-03T05:29:25.782+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T05:29:25.798+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/k9_etl_dag_v2.py took 0.043 seconds
[2024-09-03T05:29:56.461+0000] {processor.py:157} INFO - Started process (PID=1026) to work on /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T05:29:56.465+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/k9_etl_dag_v2.py for tasks to queue
[2024-09-03T05:29:56.482+0000] {logging_mixin.py:151} INFO - [2024-09-03T05:29:56.473+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T05:29:56.553+0000] {logging_mixin.py:151} INFO - [2024-09-03T05:29:56.533+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/k9_etl_dag_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/k9_etl_dag_v2.py", line 160, in <module>
    create_pet_table >> extracted_data >> transformed_data >> [load_to_file, update_check] >> insert_queries >> load_to_db >> send_notification
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 103, in __rshift__
    self.set_downstream(other)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom_arg.py", line 155, in set_downstream
    operator.set_downstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 261, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 213, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
AttributeError: '_TaskDecorator' object has no attribute 'update_relative'
[2024-09-03T05:29:56.555+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T05:29:56.627+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/k9_etl_dag_v2.py took 0.185 seconds
[2024-09-03T05:30:27.544+0000] {processor.py:157} INFO - Started process (PID=1035) to work on /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T05:30:27.545+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/k9_etl_dag_v2.py for tasks to queue
[2024-09-03T05:30:27.549+0000] {logging_mixin.py:151} INFO - [2024-09-03T05:30:27.549+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T05:30:27.565+0000] {logging_mixin.py:151} INFO - [2024-09-03T05:30:27.564+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/k9_etl_dag_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/k9_etl_dag_v2.py", line 160, in <module>
    create_pet_table >> extracted_data >> transformed_data >> [load_to_file, update_check] >> insert_queries >> load_to_db >> send_notification
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 103, in __rshift__
    self.set_downstream(other)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom_arg.py", line 155, in set_downstream
    operator.set_downstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 261, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 213, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
AttributeError: '_TaskDecorator' object has no attribute 'update_relative'
[2024-09-03T05:30:27.566+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T05:30:27.592+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/k9_etl_dag_v2.py took 0.054 seconds
[2024-09-03T05:45:41.839+0000] {processor.py:157} INFO - Started process (PID=1044) to work on /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T05:45:41.854+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/k9_etl_dag_v2.py for tasks to queue
[2024-09-03T05:45:41.881+0000] {logging_mixin.py:151} INFO - [2024-09-03T05:45:41.880+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T05:45:41.926+0000] {logging_mixin.py:151} INFO - [2024-09-03T05:45:41.920+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/k9_etl_dag_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/k9_etl_dag_v2.py", line 160, in <module>
    create_pet_table >> extracted_data >> transformed_data >> [load_to_file, update_check] >> insert_queries >> load_to_db >> send_notification
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 103, in __rshift__
    self.set_downstream(other)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom_arg.py", line 155, in set_downstream
    operator.set_downstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 261, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 213, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
AttributeError: '_TaskDecorator' object has no attribute 'update_relative'
[2024-09-03T05:45:41.927+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T05:45:42.081+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/k9_etl_dag_v2.py took 0.298 seconds
[2024-09-03T05:51:04.593+0000] {processor.py:157} INFO - Started process (PID=1053) to work on /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T05:51:04.597+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/k9_etl_dag_v2.py for tasks to queue
[2024-09-03T05:51:04.612+0000] {logging_mixin.py:151} INFO - [2024-09-03T05:51:04.611+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T05:51:04.655+0000] {logging_mixin.py:151} INFO - [2024-09-03T05:51:04.651+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/k9_etl_dag_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/k9_etl_dag_v2.py", line 160, in <module>
    create_pet_table >> extracted_data >> transformed_data >> [load_to_file, update_check] >> insert_queries >> load_to_db >> send_notification
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 103, in __rshift__
    self.set_downstream(other)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom_arg.py", line 155, in set_downstream
    operator.set_downstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 261, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 213, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
AttributeError: '_TaskDecorator' object has no attribute 'update_relative'
[2024-09-03T05:51:04.656+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T05:51:04.712+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/k9_etl_dag_v2.py took 0.128 seconds
[2024-09-03T05:51:35.158+0000] {processor.py:157} INFO - Started process (PID=1062) to work on /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T05:51:35.162+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/k9_etl_dag_v2.py for tasks to queue
[2024-09-03T05:51:35.166+0000] {logging_mixin.py:151} INFO - [2024-09-03T05:51:35.166+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T05:51:35.191+0000] {logging_mixin.py:151} INFO - [2024-09-03T05:51:35.189+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/k9_etl_dag_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/k9_etl_dag_v2.py", line 160, in <module>
    create_pet_table >> extracted_data >> transformed_data >> [load_to_file, update_check] >> insert_queries >> load_to_db >> send_notification
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 103, in __rshift__
    self.set_downstream(other)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom_arg.py", line 155, in set_downstream
    operator.set_downstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 261, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 213, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
AttributeError: '_TaskDecorator' object has no attribute 'update_relative'
[2024-09-03T05:51:35.191+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T05:51:35.219+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/k9_etl_dag_v2.py took 0.066 seconds
[2024-09-03T05:52:05.578+0000] {processor.py:157} INFO - Started process (PID=1071) to work on /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T05:52:05.583+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/k9_etl_dag_v2.py for tasks to queue
[2024-09-03T05:52:05.588+0000] {logging_mixin.py:151} INFO - [2024-09-03T05:52:05.588+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T05:52:05.611+0000] {logging_mixin.py:151} INFO - [2024-09-03T05:52:05.608+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/k9_etl_dag_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/k9_etl_dag_v2.py", line 160, in <module>
    create_pet_table >> extracted_data >> transformed_data >> [load_to_file, update_check] >> insert_queries >> load_to_db >> send_notification
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 103, in __rshift__
    self.set_downstream(other)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom_arg.py", line 155, in set_downstream
    operator.set_downstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 261, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 213, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
AttributeError: '_TaskDecorator' object has no attribute 'update_relative'
[2024-09-03T05:52:05.612+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T05:52:05.645+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/k9_etl_dag_v2.py took 0.079 seconds
[2024-09-03T05:52:36.030+0000] {processor.py:157} INFO - Started process (PID=1079) to work on /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T05:52:36.042+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/k9_etl_dag_v2.py for tasks to queue
[2024-09-03T05:52:36.062+0000] {logging_mixin.py:151} INFO - [2024-09-03T05:52:36.058+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T05:52:36.083+0000] {logging_mixin.py:151} INFO - [2024-09-03T05:52:36.077+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/k9_etl_dag_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/k9_etl_dag_v2.py", line 160, in <module>
    create_pet_table >> extracted_data >> transformed_data >> [load_to_file, update_check] >> insert_queries >> load_to_db >> send_notification
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 103, in __rshift__
    self.set_downstream(other)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom_arg.py", line 155, in set_downstream
    operator.set_downstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 261, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 213, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
AttributeError: '_TaskDecorator' object has no attribute 'update_relative'
[2024-09-03T05:52:36.083+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T05:52:36.122+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/k9_etl_dag_v2.py took 0.097 seconds
[2024-09-03T05:53:06.496+0000] {processor.py:157} INFO - Started process (PID=1088) to work on /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T05:53:06.499+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/k9_etl_dag_v2.py for tasks to queue
[2024-09-03T05:53:06.508+0000] {logging_mixin.py:151} INFO - [2024-09-03T05:53:06.507+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T05:53:06.531+0000] {logging_mixin.py:151} INFO - [2024-09-03T05:53:06.526+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/k9_etl_dag_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/k9_etl_dag_v2.py", line 160, in <module>
    create_pet_table >> extracted_data >> transformed_data >> [load_to_file, update_check] >> insert_queries >> load_to_db >> send_notification
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 103, in __rshift__
    self.set_downstream(other)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom_arg.py", line 155, in set_downstream
    operator.set_downstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 261, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 213, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
AttributeError: '_TaskDecorator' object has no attribute 'update_relative'
[2024-09-03T05:53:06.531+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T05:53:06.565+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/k9_etl_dag_v2.py took 0.087 seconds
[2024-09-03T05:53:36.886+0000] {processor.py:157} INFO - Started process (PID=1097) to work on /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T05:53:36.888+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/k9_etl_dag_v2.py for tasks to queue
[2024-09-03T05:53:36.893+0000] {logging_mixin.py:151} INFO - [2024-09-03T05:53:36.893+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T05:53:36.914+0000] {logging_mixin.py:151} INFO - [2024-09-03T05:53:36.911+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/k9_etl_dag_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/k9_etl_dag_v2.py", line 160, in <module>
    create_pet_table >> extracted_data >> transformed_data >> [load_to_file, update_check] >> insert_queries >> load_to_db >> send_notification
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 103, in __rshift__
    self.set_downstream(other)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom_arg.py", line 155, in set_downstream
    operator.set_downstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 261, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 213, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
AttributeError: '_TaskDecorator' object has no attribute 'update_relative'
[2024-09-03T05:53:36.915+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T05:53:36.942+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/k9_etl_dag_v2.py took 0.071 seconds
[2024-09-03T05:54:07.249+0000] {processor.py:157} INFO - Started process (PID=1106) to work on /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T05:54:07.252+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/k9_etl_dag_v2.py for tasks to queue
[2024-09-03T05:54:07.258+0000] {logging_mixin.py:151} INFO - [2024-09-03T05:54:07.258+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T05:54:07.300+0000] {logging_mixin.py:151} INFO - [2024-09-03T05:54:07.292+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/k9_etl_dag_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/k9_etl_dag_v2.py", line 160, in <module>
    create_pet_table >> extracted_data >> transformed_data >> [load_to_file, update_check] >> insert_queries >> load_to_db >> send_notification
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 103, in __rshift__
    self.set_downstream(other)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom_arg.py", line 155, in set_downstream
    operator.set_downstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 261, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 213, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
AttributeError: '_TaskDecorator' object has no attribute 'update_relative'
[2024-09-03T05:54:07.300+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T05:54:07.344+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/k9_etl_dag_v2.py took 0.106 seconds
[2024-09-03T05:54:37.672+0000] {processor.py:157} INFO - Started process (PID=1115) to work on /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T05:54:37.679+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/k9_etl_dag_v2.py for tasks to queue
[2024-09-03T05:54:37.690+0000] {logging_mixin.py:151} INFO - [2024-09-03T05:54:37.688+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T05:54:37.714+0000] {logging_mixin.py:151} INFO - [2024-09-03T05:54:37.711+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/k9_etl_dag_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/k9_etl_dag_v2.py", line 160, in <module>
    create_pet_table >> extracted_data >> transformed_data >> [load_to_file, update_check] >> insert_queries >> load_to_db >> send_notification
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 103, in __rshift__
    self.set_downstream(other)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom_arg.py", line 155, in set_downstream
    operator.set_downstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 261, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 213, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
AttributeError: '_TaskDecorator' object has no attribute 'update_relative'
[2024-09-03T05:54:37.714+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T05:54:37.753+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/k9_etl_dag_v2.py took 0.090 seconds
[2024-09-03T05:55:08.144+0000] {processor.py:157} INFO - Started process (PID=1124) to work on /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T05:55:08.146+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/k9_etl_dag_v2.py for tasks to queue
[2024-09-03T05:55:08.150+0000] {logging_mixin.py:151} INFO - [2024-09-03T05:55:08.150+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T05:55:08.170+0000] {logging_mixin.py:151} INFO - [2024-09-03T05:55:08.166+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/k9_etl_dag_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/k9_etl_dag_v2.py", line 160, in <module>
    create_pet_table >> extracted_data >> transformed_data >> [load_to_file, update_check] >> insert_queries >> load_to_db >> send_notification
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 103, in __rshift__
    self.set_downstream(other)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom_arg.py", line 155, in set_downstream
    operator.set_downstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 261, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 213, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
AttributeError: '_TaskDecorator' object has no attribute 'update_relative'
[2024-09-03T05:55:08.171+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T05:55:08.194+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/k9_etl_dag_v2.py took 0.056 seconds
[2024-09-03T05:55:38.531+0000] {processor.py:157} INFO - Started process (PID=1133) to work on /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T05:55:38.533+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/k9_etl_dag_v2.py for tasks to queue
[2024-09-03T05:55:38.554+0000] {logging_mixin.py:151} INFO - [2024-09-03T05:55:38.548+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T05:55:38.579+0000] {logging_mixin.py:151} INFO - [2024-09-03T05:55:38.572+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/k9_etl_dag_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/k9_etl_dag_v2.py", line 160, in <module>
    create_pet_table >> extracted_data >> transformed_data >> [load_to_file, update_check] >> insert_queries >> load_to_db >> send_notification
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 103, in __rshift__
    self.set_downstream(other)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom_arg.py", line 155, in set_downstream
    operator.set_downstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 261, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 213, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
AttributeError: '_TaskDecorator' object has no attribute 'update_relative'
[2024-09-03T05:55:38.581+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T05:55:38.606+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/k9_etl_dag_v2.py took 0.083 seconds
[2024-09-03T05:56:09.042+0000] {processor.py:157} INFO - Started process (PID=1142) to work on /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T05:56:09.044+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/k9_etl_dag_v2.py for tasks to queue
[2024-09-03T05:56:09.049+0000] {logging_mixin.py:151} INFO - [2024-09-03T05:56:09.049+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T05:56:09.076+0000] {logging_mixin.py:151} INFO - [2024-09-03T05:56:09.069+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/k9_etl_dag_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/k9_etl_dag_v2.py", line 160, in <module>
    create_pet_table >> extracted_data >> transformed_data >> [load_to_file, update_check] >> insert_queries >> load_to_db >> send_notification
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 103, in __rshift__
    self.set_downstream(other)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom_arg.py", line 155, in set_downstream
    operator.set_downstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 261, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 213, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
AttributeError: '_TaskDecorator' object has no attribute 'update_relative'
[2024-09-03T05:56:09.076+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T05:56:09.106+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/k9_etl_dag_v2.py took 0.071 seconds
[2024-09-03T05:56:39.448+0000] {processor.py:157} INFO - Started process (PID=1151) to work on /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T05:56:39.450+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/k9_etl_dag_v2.py for tasks to queue
[2024-09-03T05:56:39.455+0000] {logging_mixin.py:151} INFO - [2024-09-03T05:56:39.455+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T05:56:39.489+0000] {logging_mixin.py:151} INFO - [2024-09-03T05:56:39.484+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/k9_etl_dag_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/k9_etl_dag_v2.py", line 160, in <module>
    create_pet_table >> extracted_data >> transformed_data >> [load_to_file, update_check] >> insert_queries >> load_to_db >> send_notification
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 103, in __rshift__
    self.set_downstream(other)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom_arg.py", line 155, in set_downstream
    operator.set_downstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 261, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 213, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
AttributeError: '_TaskDecorator' object has no attribute 'update_relative'
[2024-09-03T05:56:39.489+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T05:56:39.522+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/k9_etl_dag_v2.py took 0.080 seconds
[2024-09-03T05:57:09.862+0000] {processor.py:157} INFO - Started process (PID=1160) to work on /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T05:57:09.867+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/k9_etl_dag_v2.py for tasks to queue
[2024-09-03T05:57:09.884+0000] {logging_mixin.py:151} INFO - [2024-09-03T05:57:09.883+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T05:57:09.908+0000] {logging_mixin.py:151} INFO - [2024-09-03T05:57:09.906+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/k9_etl_dag_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/k9_etl_dag_v2.py", line 160, in <module>
    create_pet_table >> extracted_data >> transformed_data >> [load_to_file, update_check] >> insert_queries >> load_to_db >> send_notification
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 103, in __rshift__
    self.set_downstream(other)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom_arg.py", line 155, in set_downstream
    operator.set_downstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 261, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 213, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
AttributeError: '_TaskDecorator' object has no attribute 'update_relative'
[2024-09-03T05:57:09.909+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T05:57:09.939+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/k9_etl_dag_v2.py took 0.084 seconds
[2024-09-03T05:57:40.334+0000] {processor.py:157} INFO - Started process (PID=1169) to work on /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T05:57:40.337+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/k9_etl_dag_v2.py for tasks to queue
[2024-09-03T05:57:40.342+0000] {logging_mixin.py:151} INFO - [2024-09-03T05:57:40.341+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T05:57:40.361+0000] {logging_mixin.py:151} INFO - [2024-09-03T05:57:40.359+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/k9_etl_dag_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/k9_etl_dag_v2.py", line 160, in <module>
    create_pet_table >> extracted_data >> transformed_data >> [load_to_file, update_check] >> insert_queries >> load_to_db >> send_notification
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 103, in __rshift__
    self.set_downstream(other)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom_arg.py", line 155, in set_downstream
    operator.set_downstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 261, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 213, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
AttributeError: '_TaskDecorator' object has no attribute 'update_relative'
[2024-09-03T05:57:40.361+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T05:57:40.404+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/k9_etl_dag_v2.py took 0.091 seconds
[2024-09-03T05:58:10.834+0000] {processor.py:157} INFO - Started process (PID=1178) to work on /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T05:58:10.837+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/k9_etl_dag_v2.py for tasks to queue
[2024-09-03T05:58:10.843+0000] {logging_mixin.py:151} INFO - [2024-09-03T05:58:10.843+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T05:58:10.863+0000] {logging_mixin.py:151} INFO - [2024-09-03T05:58:10.859+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/k9_etl_dag_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/k9_etl_dag_v2.py", line 160, in <module>
    create_pet_table >> extracted_data >> transformed_data >> [load_to_file, update_check] >> insert_queries >> load_to_db >> send_notification
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 103, in __rshift__
    self.set_downstream(other)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom_arg.py", line 155, in set_downstream
    operator.set_downstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 261, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 213, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
AttributeError: '_TaskDecorator' object has no attribute 'update_relative'
[2024-09-03T05:58:10.863+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T05:58:10.912+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/k9_etl_dag_v2.py took 0.111 seconds
[2024-09-03T05:58:41.335+0000] {processor.py:157} INFO - Started process (PID=1187) to work on /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T05:58:41.341+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/k9_etl_dag_v2.py for tasks to queue
[2024-09-03T05:58:41.346+0000] {logging_mixin.py:151} INFO - [2024-09-03T05:58:41.346+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T05:58:41.369+0000] {logging_mixin.py:151} INFO - [2024-09-03T05:58:41.363+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/k9_etl_dag_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/k9_etl_dag_v2.py", line 160, in <module>
    create_pet_table >> extracted_data >> transformed_data >> [load_to_file, update_check] >> insert_queries >> load_to_db >> send_notification
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 103, in __rshift__
    self.set_downstream(other)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom_arg.py", line 155, in set_downstream
    operator.set_downstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 261, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 213, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
AttributeError: '_TaskDecorator' object has no attribute 'update_relative'
[2024-09-03T05:58:41.369+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T05:58:41.412+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/k9_etl_dag_v2.py took 0.107 seconds
[2024-09-03T05:59:12.006+0000] {processor.py:157} INFO - Started process (PID=1196) to work on /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T05:59:12.008+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/k9_etl_dag_v2.py for tasks to queue
[2024-09-03T05:59:12.018+0000] {logging_mixin.py:151} INFO - [2024-09-03T05:59:12.017+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T05:59:12.041+0000] {logging_mixin.py:151} INFO - [2024-09-03T05:59:12.035+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/k9_etl_dag_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/k9_etl_dag_v2.py", line 160, in <module>
    create_pet_table >> extracted_data >> transformed_data >> [load_to_file, update_check] >> insert_queries >> load_to_db >> send_notification
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 103, in __rshift__
    self.set_downstream(other)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom_arg.py", line 155, in set_downstream
    operator.set_downstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 261, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 213, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
AttributeError: '_TaskDecorator' object has no attribute 'update_relative'
[2024-09-03T05:59:12.042+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T05:59:12.076+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/k9_etl_dag_v2.py took 0.081 seconds
[2024-09-03T05:59:42.485+0000] {processor.py:157} INFO - Started process (PID=1205) to work on /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T05:59:42.486+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/k9_etl_dag_v2.py for tasks to queue
[2024-09-03T05:59:42.491+0000] {logging_mixin.py:151} INFO - [2024-09-03T05:59:42.491+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T05:59:42.522+0000] {logging_mixin.py:151} INFO - [2024-09-03T05:59:42.520+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/k9_etl_dag_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/k9_etl_dag_v2.py", line 160, in <module>
    create_pet_table >> extracted_data >> transformed_data >> [load_to_file, update_check] >> insert_queries >> load_to_db >> send_notification
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 103, in __rshift__
    self.set_downstream(other)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom_arg.py", line 155, in set_downstream
    operator.set_downstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 261, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 213, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
AttributeError: '_TaskDecorator' object has no attribute 'update_relative'
[2024-09-03T05:59:42.523+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T05:59:42.547+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/k9_etl_dag_v2.py took 0.068 seconds
[2024-09-03T06:00:13.005+0000] {processor.py:157} INFO - Started process (PID=1213) to work on /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T06:00:13.007+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/k9_etl_dag_v2.py for tasks to queue
[2024-09-03T06:00:13.012+0000] {logging_mixin.py:151} INFO - [2024-09-03T06:00:13.011+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T06:00:13.047+0000] {logging_mixin.py:151} INFO - [2024-09-03T06:00:13.043+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/k9_etl_dag_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/k9_etl_dag_v2.py", line 160, in <module>
    create_pet_table >> extracted_data >> transformed_data >> [load_to_file, update_check] >> insert_queries >> load_to_db >> send_notification
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 103, in __rshift__
    self.set_downstream(other)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom_arg.py", line 155, in set_downstream
    operator.set_downstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 261, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 213, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
AttributeError: '_TaskDecorator' object has no attribute 'update_relative'
[2024-09-03T06:00:13.047+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T06:00:13.090+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/k9_etl_dag_v2.py took 0.113 seconds
[2024-09-03T06:00:43.453+0000] {processor.py:157} INFO - Started process (PID=1221) to work on /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T06:00:43.463+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/k9_etl_dag_v2.py for tasks to queue
[2024-09-03T06:00:43.475+0000] {logging_mixin.py:151} INFO - [2024-09-03T06:00:43.472+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T06:00:43.497+0000] {logging_mixin.py:151} INFO - [2024-09-03T06:00:43.492+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/k9_etl_dag_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/k9_etl_dag_v2.py", line 160, in <module>
    create_pet_table >> extracted_data >> transformed_data >> [load_to_file, update_check] >> insert_queries >> load_to_db >> send_notification
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 103, in __rshift__
    self.set_downstream(other)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom_arg.py", line 155, in set_downstream
    operator.set_downstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 261, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 213, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
AttributeError: '_TaskDecorator' object has no attribute 'update_relative'
[2024-09-03T06:00:43.498+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T06:00:43.542+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/k9_etl_dag_v2.py took 0.107 seconds
[2024-09-03T06:01:13.980+0000] {processor.py:157} INFO - Started process (PID=1230) to work on /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T06:01:13.983+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/k9_etl_dag_v2.py for tasks to queue
[2024-09-03T06:01:13.987+0000] {logging_mixin.py:151} INFO - [2024-09-03T06:01:13.986+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T06:01:14.014+0000] {logging_mixin.py:151} INFO - [2024-09-03T06:01:14.002+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/k9_etl_dag_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/k9_etl_dag_v2.py", line 160, in <module>
    create_pet_table >> extracted_data >> transformed_data >> [load_to_file, update_check] >> insert_queries >> load_to_db >> send_notification
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 103, in __rshift__
    self.set_downstream(other)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom_arg.py", line 155, in set_downstream
    operator.set_downstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 261, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 213, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
AttributeError: '_TaskDecorator' object has no attribute 'update_relative'
[2024-09-03T06:01:14.019+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T06:01:14.041+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/k9_etl_dag_v2.py took 0.068 seconds
[2024-09-03T06:01:44.463+0000] {processor.py:157} INFO - Started process (PID=1239) to work on /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T06:01:44.465+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/k9_etl_dag_v2.py for tasks to queue
[2024-09-03T06:01:44.477+0000] {logging_mixin.py:151} INFO - [2024-09-03T06:01:44.472+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T06:01:44.501+0000] {logging_mixin.py:151} INFO - [2024-09-03T06:01:44.498+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/k9_etl_dag_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/k9_etl_dag_v2.py", line 160, in <module>
    create_pet_table >> extracted_data >> transformed_data >> [load_to_file, update_check] >> insert_queries >> load_to_db >> send_notification
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 103, in __rshift__
    self.set_downstream(other)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom_arg.py", line 155, in set_downstream
    operator.set_downstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 261, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 213, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
AttributeError: '_TaskDecorator' object has no attribute 'update_relative'
[2024-09-03T06:01:44.503+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T06:01:44.543+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/k9_etl_dag_v2.py took 0.090 seconds
[2024-09-03T06:21:24.502+0000] {processor.py:157} INFO - Started process (PID=1248) to work on /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T06:21:24.504+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/k9_etl_dag_v2.py for tasks to queue
[2024-09-03T06:21:24.507+0000] {logging_mixin.py:151} INFO - [2024-09-03T06:21:24.507+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T06:21:24.534+0000] {logging_mixin.py:151} INFO - [2024-09-03T06:21:24.522+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/k9_etl_dag_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/k9_etl_dag_v2.py", line 160, in <module>
    create_pet_table >> extracted_data >> transformed_data >> [load_to_file, update_check] >> insert_queries >> load_to_db >> send_notification
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 103, in __rshift__
    self.set_downstream(other)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom_arg.py", line 155, in set_downstream
    operator.set_downstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 261, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 213, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
AttributeError: '_TaskDecorator' object has no attribute 'update_relative'
[2024-09-03T06:21:24.535+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T06:21:24.557+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/k9_etl_dag_v2.py took 0.062 seconds
[2024-09-03T06:24:05.514+0000] {processor.py:157} INFO - Started process (PID=1257) to work on /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T06:24:05.518+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/k9_etl_dag_v2.py for tasks to queue
[2024-09-03T06:24:05.545+0000] {logging_mixin.py:151} INFO - [2024-09-03T06:24:05.544+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T06:24:05.594+0000] {logging_mixin.py:151} INFO - [2024-09-03T06:24:05.590+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/k9_etl_dag_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/k9_etl_dag_v2.py", line 160, in <module>
    create_pet_table >> extracted_data >> transformed_data >> [load_to_file, update_check] >> insert_queries >> load_to_db >> send_notification
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 103, in __rshift__
    self.set_downstream(other)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom_arg.py", line 155, in set_downstream
    operator.set_downstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 261, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 213, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
AttributeError: '_TaskDecorator' object has no attribute 'update_relative'
[2024-09-03T06:24:05.595+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T06:24:05.679+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/k9_etl_dag_v2.py took 0.196 seconds
[2024-09-03T06:24:36.005+0000] {processor.py:157} INFO - Started process (PID=1266) to work on /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T06:24:36.008+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/k9_etl_dag_v2.py for tasks to queue
[2024-09-03T06:24:36.015+0000] {logging_mixin.py:151} INFO - [2024-09-03T06:24:36.015+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T06:24:36.045+0000] {logging_mixin.py:151} INFO - [2024-09-03T06:24:36.038+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/k9_etl_dag_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/k9_etl_dag_v2.py", line 160, in <module>
    create_pet_table >> extracted_data >> transformed_data >> [load_to_file, update_check] >> insert_queries >> load_to_db >> send_notification
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 103, in __rshift__
    self.set_downstream(other)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom_arg.py", line 155, in set_downstream
    operator.set_downstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 261, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 213, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
AttributeError: '_TaskDecorator' object has no attribute 'update_relative'
[2024-09-03T06:24:36.045+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T06:24:36.098+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/k9_etl_dag_v2.py took 0.102 seconds
[2024-09-03T06:29:29.049+0000] {processor.py:157} INFO - Started process (PID=1275) to work on /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T06:29:29.053+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/k9_etl_dag_v2.py for tasks to queue
[2024-09-03T06:29:29.066+0000] {logging_mixin.py:151} INFO - [2024-09-03T06:29:29.065+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T06:29:29.115+0000] {logging_mixin.py:151} INFO - [2024-09-03T06:29:29.102+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/k9_etl_dag_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/k9_etl_dag_v2.py", line 160, in <module>
    create_pet_table >> extracted_data >> transformed_data >> [load_to_file, update_check] >> insert_queries >> load_to_db >> send_notification
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 103, in __rshift__
    self.set_downstream(other)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom_arg.py", line 155, in set_downstream
    operator.set_downstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 261, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 213, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
AttributeError: '_TaskDecorator' object has no attribute 'update_relative'
[2024-09-03T06:29:29.120+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/k9_etl_dag_v2.py
[2024-09-03T06:29:29.175+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/k9_etl_dag_v2.py took 0.140 seconds
